name: Daily YouTube Upload

on:
  schedule:
    # Runs at 2 PM UTC daily (adjust timezone as needed)
    - cron: '0 14 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install google-auth google-auth-oauthlib google-api-python-client
        pip install requests pillow openai
    
    - name: Generate Video Content
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      run: python generate_video.py
    
    - name: Upload to YouTube
      env:
        YOUTUBE_CREDENTIALS: ${{ secrets.YOUTUBE_CREDENTIALS }}
      run: python upload_to_youtube.py
